version: '3'

services:

  paintchat:
    build: .
    ports:
      - "8080"
    labels:
      - "traefik.backend=paintchat"
      - "traefik.frontend.rule=Host:paintchat.localhost"
      - "traefik.port=8080"
      - "traefik.enable=true"
    depends_on:
      - cassandra

  traefik:
    image: traefik
    command: --api --docker --docker.domain=localhost --docker.exposedbydefault=false --logLevel=INFO
    ports:
      - "8080:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  cassandra:
    image: cassandra
    volumes:
      - cassandra.data:/var/lib/cassandra

volumes:
  cassandra.data:
