version: '3'

services:

  paintchat:
    build: .
    ports:
      - "8080"
    depends_on:
      - cassandra

  nginx:
    build: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - paintchat

  cassandra:
    image: cassandra
    volumes:
      - cassandra.data:/var/lib/cassandra

volumes:
  cassandra.data:
